In [3]:
import os

In [4]:
import pandas as pd

### Download neccessary data

In [5]:
os.system('wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-01.csv.gz -O tripdata.csv.gz')

--2023-01-26 13:15:37--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-01.csv.gz
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/513814948/d3904232-1a2b-431b-803d-0ee802cd14fc?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20230126%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230126T121540Z&X-Amz-Expires=300&X-Amz-Signature=2b7c29c5f75dd82c40b92e354c20b8a6b63c583599236f26bb2fb27d186d0393&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=513814948&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2019-01.csv.gz&response-content-type=application%2Foctet-stream [following]
--2023-01-26 13:15:41--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/513814948/d3904232-1a2b-431b-803d-0ee802cd14fc?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20230126%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230126T121540Z&X-Amz-Expires=300&X-Amz-Signature=2b7c29c5f75dd82c40b92e354c20b8a6b63c583599236f26bb2fb27d186d0393&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=513814948&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2019-01.csv.gz&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11099245 (11M) [application/octet-stream]
Saving to: ‘tripdata.csv.gz’

     0K .......... .......... .......... .......... ..........  0%  483K 22s
    50K .......... .......... .......... .......... ..........  0% 1.02M 16s
   100K .......... .......... .......... .......... ..........  1% 2.58M 12s
   150K .......... .......... .......... .......... ..........  1% 1.19M 11s
   200K .......... .......... .......... .......... ..........  2% 4.67M 9s
   250K .......... .......... .......... .......... ..........  2% 4.26M 8s
   300K .......... .......... .......... .......... ..........  3% 3.88M 7s
   350K .......... .......... .......... .......... ..........  3% 2.63M 7s
   400K .......... .......... .......... .......... ..........  4% 2.40M 7s
   450K .......... .......... .......... .......... ..........  4% 2.82M 6s
   500K .......... .......... .......... .......... ..........  5% 3.31M 6s
   550K .......... .......... .......... .......... ..........  5% 10.6M 5s
   600K .......... .......... .......... .......... ..........  5% 3.45M 5s
   650K .......... .......... .......... .......... ..........  6% 3.71M 5s
   700K .......... .......... .......... .......... ..........  6% 1.51M 5s
   750K .......... .......... .......... .......... ..........  7% 10.8M 5s
   800K .......... .......... .......... .......... ..........  7% 3.68M 5s
   850K .......... .......... .......... .......... ..........  8% 3.18M 5s
   900K .......... .......... .......... .......... ..........  8% 2.39M 5s
   950K .......... .......... .......... .......... ..........  9% 14.7M 4s
  1000K .......... .......... .......... .......... ..........  9% 4.56M 4s
  1050K .......... .......... .......... .......... .......... 10% 4.01M 4s
  1100K .......... .......... .......... .......... .......... 10% 2.72M 4s
  1150K .......... .......... .......... .......... .......... 11% 5.35M 4s
  1200K .......... .......... .......... .......... .......... 11% 2.86M 4s
  1250K .......... .......... .......... .......... .......... 11% 4.06M 4s
  1300K .......... .......... .......... .......... .......... 12% 5.05M 4s
  1350K .......... .......... .......... .......... .......... 12% 4.65M 4s
  1400K .......... .......... .......... .......... .......... 13% 4.90M 4s
  1450K .......... .......... .......... .......... .......... 13% 4.44M 3s
  1500K .......... .......... .......... .......... .......... 14% 5.76M 3s
  1550K .......... .......... .......... .......... .......... 14% 4.61M 3s
  1600K .......... .......... .......... .......... .......... 15% 3.31M 3s
  1650K .......... .......... .......... .......... .......... 15% 5.98M 3s
  1700K .......... .......... .......... .......... .......... 16% 3.48M 3s
  1750K .......... .......... .......... .......... .......... 16% 6.13M 3s
  1800K .......... .......... .......... .......... .......... 17% 4.77M 3s
  1850K .......... .......... .......... .......... .......... 17% 4.27M 3s
  1900K .......... .......... .......... .......... .......... 17% 6.08M 3s
  1950K .......... .......... .......... .......... .......... 18% 5.96M 3s
  2000K .......... .......... .......... .......... .......... 18% 4.79M 3s
  2050K .......... .......... .......... .......... .......... 19% 3.11M 3s
  2100K .......... .......... .......... .......... .......... 19% 1.72M 3s
  2150K .......... .......... .......... .......... .......... 20% 9.51M 3s
  2200K .......... .......... .......... .......... .......... 20% 3.57M 3s
  2250K .......... .......... .......... .......... .......... 21% 10.6M 3s
  2300K .......... .......... .......... .......... .......... 21% 3.37M 3s
  2350K .......... .......... .......... .......... .......... 22% 11.4M 3s
  2400K .......... .......... .......... .......... .......... 22% 4.17M 3s
  2450K .......... .......... .......... .......... .......... 23% 3.27M 3s
  2500K .......... .......... .......... .......... .......... 23% 2.48M 3s
  2550K .......... .......... .......... .......... .......... 23% 3.04M 3s
  2600K .......... .......... .......... .......... .......... 24% 2.54M 3s
  2650K .......... .......... .......... .......... .......... 24% 5.17M 3s
  2700K .......... .......... .......... .......... .......... 25% 5.32M 3s
  2750K .......... .......... .......... .......... .......... 25% 5.58M 2s
  2800K .......... .......... .......... .......... .......... 26% 4.23M 2s
  2850K .......... .......... .......... .......... .......... 26% 5.10M 2s
  2900K .......... .......... .......... .......... .......... 27% 3.49M 2s
  2950K .......... .......... .......... .......... .......... 27% 3.17M 2s
  3000K .......... .......... .......... .......... .......... 28% 5.68M 2s
  3050K .......... .......... .......... .......... .......... 28% 5.57M 2s
  3100K .......... .......... .......... .......... .......... 29% 5.46M 2s
  3150K .......... .......... .......... .......... .......... 29% 3.34M 2s
  3200K .......... .......... .......... .......... .......... 29% 4.39M 2s
  3250K .......... .......... .......... .......... .......... 30% 7.18M 2s
  3300K .......... .......... .......... .......... .......... 30% 4.84M 2s
  3350K .......... .......... .......... .......... .......... 31% 5.46M 2s
  3400K .......... .......... .......... .......... .......... 31% 4.17M 2s
  3450K .......... .......... .......... .......... .......... 32% 4.28M 2s
  3500K .......... .......... .......... .......... .......... 32% 2.69M 2s
  3550K .......... .......... .......... .......... .......... 33% 2.42M 2s
  3600K .......... .......... .......... .......... .......... 33% 2.91M 2s
  3650K .......... .......... .......... .......... .......... 34% 5.05M 2s
  3700K .......... .......... .......... .......... .......... 34% 3.68M 2s
  3750K .......... .......... .......... .......... .......... 35% 2.22M 2s
  3800K .......... .......... .......... .......... .......... 35% 1.36M 2s
  3850K .......... .......... .......... .......... .......... 35% 4.02M 2s
  3900K .......... .......... .......... .......... .......... 36% 2.63M 2s
  3950K .......... .......... .......... .......... .......... 36% 6.96M 2s
  4000K .......... .......... .......... .......... .......... 37% 8.27M 2s
  4050K .......... .......... .......... .......... .......... 37% 7.87M 2s
  4100K .......... .......... .......... .......... .......... 38% 6.45M 2s
  4150K .......... .......... .......... .......... .......... 38% 5.62M 2s
  4200K .......... .......... .......... .......... .......... 39% 5.77M 2s

  4250K .......... .......... .......... .......... .......... 39%  170K 2s
  4300K .......... .......... .......... .......... .......... 40% 4.25M 2s
  4350K .......... .......... .......... .......... .......... 40% 9.22M 2s
  4400K .......... .......... .......... .......... .......... 41% 5.86M 2s
  4450K .......... .......... .......... .......... .......... 41% 6.71M 2s
  4500K .......... .......... .......... .......... .......... 41% 6.83M 2s
  4550K .......... .......... .......... .......... .......... 42% 5.25M 2s
  4600K .......... .......... .......... .......... .......... 42% 6.58M 2s
  4650K .......... .......... .......... .......... .......... 43% 5.02M 2s
  4700K .......... .......... .......... .......... .......... 43% 6.34M 2s
  4750K .......... .......... .......... .......... .......... 44% 7.24M 2s
  4800K .......... .......... .......... .......... .......... 44% 6.45M 2s
  4850K .......... .......... .......... .......... .......... 45% 4.61M 2s
  4900K .......... .......... .......... .......... .......... 45% 1.93M 2s
  4950K .......... .......... .......... .......... .......... 46% 15.5M 2s
  5000K .......... .......... .......... .......... .......... 46% 5.14M 2s
  5050K .......... .......... .......... .......... .......... 47% 2.82M 2s
  5100K .......... .......... .......... .......... .......... 47% 4.15M 2s
  5150K .......... .......... .......... .......... .......... 47% 8.81M 2s
  5200K .......... .......... .......... .......... .......... 48% 3.62M 2s
  5250K .......... .......... .......... .......... .......... 48% 7.97M 2s
  5300K .......... .......... .......... .......... .......... 49% 7.99M 2s
  5350K .......... .......... .......... .......... .......... 49% 3.09M 2s
  5400K .......... .......... .......... .......... .......... 50% 9.69M 2s
  5450K .......... .......... .......... .......... .......... 50% 7.17M 2s
  5500K .......... .......... .......... .......... .......... 51% 6.24M 2s
  5550K .......... .......... .......... .......... .......... 51% 4.75M 2s
  5600K .......... .......... .......... .......... .......... 52% 3.95M 2s
  5650K .......... .......... .......... .......... .......... 52% 9.69M 2s
  5700K .......... .......... .......... .......... .......... 53% 5.69M 2s
  5750K .......... .......... .......... .......... .......... 53% 6.27M 2s
  5800K .......... .......... .......... .......... .......... 53% 5.35M 2s
  5850K .......... .......... .......... .......... .......... 54% 5.86M 2s
  5900K .......... .......... .......... .......... .......... 54% 9.26M 1s
  5950K .......... .......... .......... .......... .......... 55% 3.12M 1s
  6000K .......... .......... .......... .......... .......... 55% 7.20M 1s
  6050K .......... .......... .......... .......... .......... 56% 7.04M 1s
  6100K .......... .......... .......... .......... .......... 56% 8.23M 1s
  6150K .......... .......... .......... .......... .......... 57% 7.27M 1s
  6200K .......... .......... .......... .......... .......... 57% 4.87M 1s
  6250K .......... .......... .......... .......... .......... 58% 6.44M 1s
  6300K .......... .......... .......... .......... .......... 58% 4.71M 1s
  6350K .......... .......... .......... .......... .......... 59% 5.11M 1s
  6400K .......... .......... .......... .......... .......... 59% 4.20M 1s
  6450K .......... .......... .......... .......... .......... 59% 3.17M 1s
  6500K .......... .......... .......... .......... .......... 60% 1.32M 1s
  6550K .......... .......... .......... .......... .......... 60% 5.94M 1s
  6600K .......... .......... .......... .......... .......... 61% 3.89M 1s
  6650K .......... .......... .......... .......... .......... 61% 4.94M 1s
  6700K .......... .......... .......... .......... .......... 62% 4.34M 1s
  6750K .......... .......... .......... .......... .......... 62% 5.45M 1s
  6800K .......... .......... .......... .......... .......... 63% 3.08M 1s
  6850K .......... .......... .......... .......... .......... 63% 3.51M 1s
  6900K .......... .......... .......... .......... .......... 64% 5.16M 1s
  6950K .......... .......... .......... .......... .......... 64% 4.37M 1s
  7000K .......... .......... .......... .......... .......... 65% 4.97M 1s
  7050K .......... .......... .......... .......... .......... 65% 4.84M 1s
  7100K .......... .......... .......... .......... .......... 65% 4.28M 1s
  7150K .......... .......... .......... .......... .......... 66%  338K 1s
  7200K .......... .......... .......... .......... .......... 66% 8.95M 1s
  7250K .......... .......... .......... .......... .......... 67% 7.12M 1s
  7300K .......... .......... .......... .......... .......... 67% 8.09M 1s
  7350K .......... .......... .......... .......... .......... 68% 5.47M 1s
  7400K .......... .......... .......... .......... .......... 68% 6.77M 1s
  7450K .......... .......... .......... .......... .......... 69% 6.00M 1s
  7500K .......... .......... .......... .......... .......... 69% 6.59M 1s
  7550K .......... .......... .......... .......... .......... 70% 3.71M 1s
  7600K .......... .......... .......... .......... .......... 70% 8.15M 1s
  7650K .......... .......... .......... .......... .......... 71% 6.45M 1s
  7700K .......... .......... .......... .......... .......... 71% 1.37M 1s
  7750K .......... .......... .......... .......... .......... 71% 2.57M 1s
  7800K .......... .......... .......... .......... .......... 72% 5.66M 1s
  7850K .......... .......... .......... .......... .......... 72% 7.02M 1s
  7900K .......... .......... .......... .......... .......... 73% 5.78M 1s
  7950K .......... .......... .......... .......... .......... 73% 5.46M 1s
  8000K .......... .......... .......... .......... .......... 74% 5.30M 1s
  8050K .......... .......... .......... .......... .......... 74% 9.64M 1s
  8100K .......... .......... .......... .......... .......... 75% 3.93M 1s
  8150K .......... .......... .......... .......... .......... 75% 5.41M 1s
  8200K .......... .......... .......... .......... .......... 76% 8.18M 1s
  8250K .......... .......... .......... .......... .......... 76% 4.82M 1s
  8300K .......... .......... .......... .......... .......... 77% 7.15M 1s
  8350K .......... .......... .......... .......... .......... 77% 1.63M 1s
  8400K .......... .......... .......... .......... .......... 77%  207M 1s
  8450K .......... .......... .......... .......... .......... 78% 2.15M 1s
  8500K .......... .......... .......... .......... .......... 78% 4.29M 1s
  8550K .......... .......... .......... .......... .......... 79% 4.40M 1s
  8600K .......... .......... .......... .......... .......... 79% 3.92M 1s
  8650K .......... .......... .......... .......... .......... 80% 5.21M 1s
  8700K .......... .......... .......... .......... .......... 80% 7.64M 1s
  8750K .......... .......... .......... .......... .......... 81% 4.37M 1s
  8800K .......... .......... .......... .......... .......... 81% 4.84M 1s
  8850K .......... .......... .......... .......... .......... 82% 6.65M 1s
  8900K .......... .......... .......... .......... .......... 82% 7.56M 1s
  8950K .......... .......... .......... .......... .......... 83% 3.69M 1s
  9000K .......... .......... .......... .......... .......... 83% 12.5M 1s
  9050K .......... .......... .......... .......... .......... 83% 4.84M 1s
  9100K .......... .......... .......... .......... .......... 84% 4.69M 0s
  9150K .......... .......... .......... .......... .......... 84% 6.50M 0s
  9200K .......... .......... .......... .......... .......... 85% 6.02M 0s
  9250K .......... .......... .......... .......... .......... 85% 5.58M 0s
  9300K .......... .......... .......... .......... .......... 86% 5.21M 0s
  9350K .......... .......... .......... .......... .......... 86% 2.65M 0s
  9400K .......... .......... .......... .......... .......... 87% 8.82M 0s
  9450K .......... .......... .......... .......... .......... 87% 4.58M 0s
  9500K .......... .......... .......... .......... .......... 88% 3.23M 0s
  9550K .......... .......... .......... .......... .......... 88% 6.08M 0s
  9600K .......... .......... .......... .......... .......... 89% 1.85M 0s
  9650K .......... .......... .......... .......... .......... 89% 5.46M 0s
  9700K .......... .......... .......... .......... .......... 89% 4.01M 0s
  9750K .......... .......... .......... .......... .......... 90% 3.21M 0s
  9800K .......... .......... .......... .......... .......... 90% 11.2M 0s
  9850K .......... .......... .......... .......... .......... 91% 2.75M 0s
  9900K .......... .......... .......... .......... .......... 91% 4.44M 0s

  9950K .......... .......... .......... .......... .......... 92% 7.81M 0s
 10000K .......... .......... .......... .......... .......... 92% 4.70M 0s
 10050K .......... .......... .......... .......... .......... 93% 4.43M 0s
 10100K .......... .......... .......... .......... .......... 93% 5.76M 0s
 10150K .......... .......... .......... .......... .......... 94% 6.19M 0s
 10200K .......... .......... .......... .......... .......... 94% 6.96M 0s
 10250K .......... .......... .......... .......... .......... 95% 3.01M 0s
 10300K .......... .......... .......... .......... .......... 95% 9.90M 0s
 10350K .......... .......... .......... .......... .......... 95% 4.46M 0s
 10400K .......... .......... .......... .......... .......... 96% 7.25M 0s
 10450K .......... .......... .......... .......... .......... 96% 3.55M 0s
 10500K .......... .......... .......... .......... .......... 97% 8.21M 0s
 10550K .......... .......... .......... .......... .......... 97% 3.94M 0s
 10600K .......... .......... .......... .......... .......... 98% 6.47M 0s
 10650K .......... .......... .......... .......... .......... 98% 4.40M 0s
 10700K .......... .......... .......... .......... .......... 99% 12.3M 0s
 10750K .......... .......... .......... .......... .......... 99% 6.50M 0s
 10800K .......... .......... .......... .........            100% 5.42M=3.0s

2023-01-26 13:15:45 (3.54 MB/s) - ‘tripdata.csv.gz’ saved [11099245/11099245]

0

In [6]:
os.system('wget https://s3.amazonaws.com/nyc-tlc/misc/taxi+_zone_lookup.csv -O zones.csv')

--2023-01-26 13:15:54--  https://s3.amazonaws.com/nyc-tlc/misc/taxi+_zone_lookup.csv
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.217.107.38, 52.216.232.141, 52.217.103.216, ...
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.217.107.38|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12322 (12K) [application/octet-stream]
Saving to: ‘zones.csv’

     0K .......... ..                                         100% 4.89M=0.002s

2023-01-26 13:15:55 (4.89 MB/s) - ‘zones.csv’ saved [12322/12322]

0

In [5]:
df_trip = pd.read_csv('tripdata.csv.gz')

In [6]:
df_trip.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2018-12-21 15:17:29,2018-12-21 15:18:57,N,1,264,264,5,0.00,3.0,0.5,0.5,0.00,0.0,NaN,0.3,4.30,2,1,NaN
1,2,2019-01-01 00:10:16,2019-01-01 00:16:32,N,1,97,49,2,0.86,6.0,0.5,0.5,0.00,0.0,NaN,0.3,7.30,2,1,NaN
2,2,2019-01-01 00:27:11,2019-01-01 00:31:38,N,1,49,189,2,0.66,4.5,0.5,0.5,0.00,0.0,NaN,0.3,5.80,1,1,NaN
3,2,2019-01-01 00:46:20,2019-01-01 01:04:54,N,1,189,17,2,2.68,13.5,0.5,0.5,2.96,0.0,NaN,0.3,19.71,1,1,NaN
4,2,2019-01-01 00:19:06,2019-01-01 00:39:43,N,1,82,258,1,4.53,18.0,0.5,0.5,0.00,0.0,NaN,0.3,19.30,2,1,NaN

In [7]:
df_trip.lpep_pickup_datetime = pd.to_datetime(df_trip.lpep_pickup_datetime)
df_trip.lpep_dropoff_datetime = pd.to_datetime(df_trip.lpep_dropoff_datetime)

In [8]:
df_zones = pd.read_csv('zones.csv')

In [9]:
df_zones.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [10]:
df = df_trip.merge(df_zones, left_on='PULocationID', right_on='LocationID')
df = df.merge(df_zones, left_on='DOLocationID', right_on='LocationID', suffixes=('_PU', '_DO'))

In [11]:
# df = df[(df['Zone_DO'] != 'NV') & (df['Zone_PU'] != 'NV')]

In [12]:
df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,trip_type,congestion_surcharge,LocationID_PU,Borough_PU,Zone_PU,service_zone_PU,LocationID_DO,Borough_DO,Zone_DO,service_zone_DO
0,2,2018-12-21 15:17:29,2018-12-21 15:18:57,N,1,264,264,5,0.00,3.0,...,1,NaN,264,Unknown,NV,NaN,264,Unknown,NV,NaN
1,2,2019-01-01 00:36:29,2019-01-01 00:36:29,N,1,264,264,1,0.00,2.5,...,1,NaN,264,Unknown,NV,NaN,264,Unknown,NV,NaN
2,2,2019-01-01 00:22:43,2019-01-01 00:54:37,N,1,264,264,1,7.28,28.5,...,1,NaN,264,Unknown,NV,NaN,264,Unknown,NV,NaN
3,2,2019-01-01 04:43:26,2019-01-01 04:43:26,N,1,264,264,1,0.00,2.5,...,1,NaN,264,Unknown,NV,NaN,264,Unknown,NV,NaN
4,2,2019-01-01 05:46:04,2019-01-01 05:46:04,N,1,264,264,1,0.00,2.5,...,1,NaN,264,Unknown,NV,NaN,264,Unknown,NV,NaN

In [13]:
df.dtypes

VendorID                          int64
lpep_pickup_datetime     datetime64[ns]
lpep_dropoff_datetime    datetime64[ns]
store_and_fwd_flag               object
RatecodeID                        int64
PULocationID                      int64
DOLocationID                      int64
passenger_count                   int64
trip_distance                   float64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
ehail_fee                       float64
improvement_surcharge           float64
total_amount                    float64
payment_type                      int64
trip_type                         int64
congestion_surcharge            float64
LocationID_PU                     int64
Borough_PU                       object
Zone_PU                          object
service_zone_PU                  object
LocationID_DO                     int64
Borough_DO                       object
Zone_DO                          object
service_zone_DO                  object
dtype: object

### Q3

In [45]:
df[(df['lpep_pickup_datetime'].dt.date.astype(str) == '2019-01-15') & (df['lpep_dropoff_datetime'].dt.date.astype(str) == '2019-01-15')].shape[0]

20530

### Q4

In [56]:
df.iloc[df['trip_distance'].idxmax()]['lpep_pickup_datetime']

Timestamp('2019-01-15 19:27:58')

### Q5

In [59]:
df['lpep_pickup_date'] = df['lpep_pickup_datetime'].dt.date
df['lpep_dropoff_date'] = df['lpep_dropoff_datetime'].dt.date

In [76]:
df[(df['lpep_pickup_date'].astype(str) == '2019-01-01') & (df['passenger_count'] == 2)].shape[0]

1282

In [79]:
df[(df['lpep_pickup_date'].astype(str) == '2019-01-01') & (df['passenger_count'] == 3)].shape[0]

254

### Q6

In [15]:
%%timeit

df.iloc[df[(df['Zone_PU'] == 'Astoria')]['tip_amount'].idxmax()]['Zone_DO']

29.5 ms ± 306 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)